# 1. Managed PostgreSQL
databases:
  - name: postgres-db
    databaseName: url_shortener_db
    user: url_shortener_user
    plan: free

# 2. Managed Redis & Spring Boot App
services:
  - type: redis
    name: redis-cache
    plan: free
    ipAllowList: [] 

  - type: web
    name: url-shortener-app
    runtime: image 
    plan: free
    image:
      url: docker.io/piyush200225/url-shortener:1.0.0
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
          
      - key: SPRING_DATA_REDIS_HOST
        fromService:
          type: redis
          name: redis-cache
          property: host
      - key: SPRING_DATA_REDIS_PORT
        fromService:
          type: redis
          name: redis-cache
          property: port
          
      - key: CACHE_TYPE
        value: redis
