spring.application.name=url-shortner
spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port = 8080

spring.data.redis.host = ${redis_host}
spring.data.redis.port = ${redis_port}
#spring.data.redis.username = ${redis_username}
#spring.data.redis.password = ${redis_password}
spring.cache.type=${cache_type}
